version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/guardrail_sentinel_backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "Ladu244-ui"
    assignees:
      - "Ladu244-ui"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    reviewers:
      - "Ladu244-ui"
    assignees:
      - "Ladu244-ui"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
